#!/bin/sh
# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: GPL-3.0-or-later

here="$(dirname "$(readlink -f "$0")")"
exec "$here/usr/lib/sdflens/sdflens" "$@"
