# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""About dialog with the copyright, license and third-party license notices."""

from __future__ import annotations

from pathlib import Path

from PySide6.QtGui import QFontDatabase
from PySide6.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QLabel,
    QPlainTextEdit,
    QVBoxLayout,
    QWidget,
)

from . import __version__

__all__ = ["AboutDialog"]

# Generated by packaging/make_notices.py when the application is built.
_NOTICES = Path(__file__).parent / "THIRD-PARTY-NOTICES.txt"

_COLUMNS = 90
_LINES = 40


class AboutDialog(QDialog):
    """Application information above the read-only third-party license notices."""

    def __init__(self, parent: QWidget | None = None) -> None:
        """Create the dialog."""
        super().__init__(parent)
        self.setWindowTitle(self.tr("About"))
        summary = QLabel(
            self.tr(
                "<h3>sdflens {version}</h3>"
                "<p>3D and 2D viewer for ISO 25178 SDF and x3p files.</p>"
                "<p>Copyright &copy; 2026 Thomas Ascher</p>"
                '<p>License: <a href="https://spdx.org/licenses/GPL-3.0-or-later.html">'
                "GPL-3.0-or-later</a></p>"
                '<p>Source code: <a href="https://github.com/aschet/sdflens">'
                "https://github.com/aschet/sdflens</a></p>"
                "<p>Third-party licenses:</p>"
            ).format(version=__version__),
            self,
        )
        summary.setOpenExternalLinks(True)
        self.text = QPlainTextEdit(self._notices(), self)
        self.text.setReadOnly(True)
        self.text.setFont(QFontDatabase.systemFont(QFontDatabase.SystemFont.FixedFont))
        buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Close, self)
        buttons.rejected.connect(self.reject)

        layout = QVBoxLayout(self)
        layout.addWidget(summary)
        layout.addWidget(self.text)
        layout.addWidget(buttons)
        metrics = self.text.fontMetrics()
        self.resize(_COLUMNS * metrics.averageCharWidth(), _LINES * metrics.lineSpacing())

    def _notices(self) -> str:
        try:
            return _NOTICES.read_text(encoding="utf-8")
        except OSError:
            return self.tr("The third-party license notices are generated when building sdflens.")
