# SPDX-FileCopyrightText: 2026 Thomas Ascher <thomas.ascher@gmx.at>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Regenerate the colormap tables and license notice; developers only, needs matplotlib.

Usage: ``python tools/generate_colormaps.py`` in an environment with matplotlib installed.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
import numpy as np

PACKAGE = Path(__file__).parent.parent / "src" / "sdflens"
LICENSES = Path(__file__).parent.parent / "LICENSES"

# Display name and matplotlib name; the order is the order in the user interface.
COLORMAPS = (
    ("Viridis", "viridis"),
    ("Plasma", "plasma"),
    ("Inferno", "inferno"),
    ("Magma", "magma"),
    ("Turbo", "turbo"),
)

DATA_HEADER = """\
# SPDX-FileCopyrightText: 2015 Nathaniel J. Smith, Stefan van der Walt, Eric Firing
# SPDX-FileCopyrightText: 2019 Google LLC
#
# SPDX-License-Identifier: CC0-1.0 AND Apache-2.0

\"\"\"Colormap tables, generated by tools/generate_colormaps.py; do not edit.

Each table holds 256 sRGB colors as 768 bytes in hexadecimal; the license is listed in
colormap_notices.txt.
\"\"\"

TABLES: dict[str, str] = {
"""

NOTICES = """\
Viridis, Plasma, Inferno and Magma
Copyright Nathaniel J. Smith and Stefan van der Walt (and, for Viridis, Eric Firing).
Released under CC0 1.0 Universal, https://creativecommons.org/publicdomain/zero/1.0/
Source: https://github.com/BIDS/colormap

Turbo
Copyright 2019 Google LLC. Author: Anton Mikhailov.
Licensed under the Apache License, Version 2.0, the full text follows.
Source: https://gist.github.com/mikhailov-work/ee72ba4191942acecc03fe6da94fc73f

{apache}
"""


def table(name: str) -> str:
    """Return the 256 colors of the matplotlib colormap ``name`` as hexadecimal text."""
    colors = matplotlib.colormaps[name](np.arange(256))[:, :3]
    return bytes(np.rint(colors * 255).astype(np.uint8).ravel()).hex()


def main() -> None:
    """Write colormap_data.py and colormap_notices.txt into the package."""
    lines = [DATA_HEADER]
    for display, name in COLORMAPS:
        digits = table(name)
        chunks = [digits[start : start + 88] for start in range(0, len(digits), 88)]
        lines.append(f'    "{display}": (\n')
        lines.extend(f'        "{chunk}"\n' for chunk in chunks)
        lines.append("    ),\n")
    lines.append("}\n")
    (PACKAGE / "colormap_data.py").write_text("".join(lines), encoding="utf-8", newline="\n")
    notices = NOTICES.format(
        apache=(LICENSES / "Apache-2.0.txt").read_text(encoding="utf-8").strip()
    )
    (PACKAGE / "colormap_notices.txt").write_text(notices, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
